baseURL = "https://example.org/"
locale = "en-us"
title = "Drew Council"
theme = "typo"

[caches.images]
dir = ":cacheDir/images"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "catppuccin-mocha"

[module]

[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "resume/resume_drew_council.pdf"
target = "content/resume/resume.pdf"

[[module.imports]]
path = "cj.rs/gohugo-asciinema"

[params]
# Meta description
description = ""
# Appearance settings
theme = "dark"
colorPalette = "catpuccin-dark"
hideHeader = false
# Intro on main page, content is markdown
homeIntroContent = """
**Hi!** I'm Drew, also known as [@bizmyth](/about).

I'm an NYC-based software engineer working at [Dirac, Inc](https://www.diracinc.com/).

I love **backend and infrastructure**. I program a lot in **Go, Python, Rust, and C/C++**.

I'm also a big fan of **Nix and NixOS**. Check out [my NixOS config](https://github.com/AndrewCouncil/nixconf)!

I occassionally write about technologies and topics that interest me here.
"""
# Collection to display on home
homeCollectionTitle = "posts"
homeCollection = "posts"
# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = "Jan 2 2006"

[params.asciinema.defaults]
theme = "catppuccin-mocha"
loop = true
autoPlay = true
speed = 1.0
terminalFontFamily = "JetBrains Mono, ui-monospace, SF Mono, Cascadia Code, Roboto Mono, Consolas, Courier New, monospace"

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = true
home = "home"

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/drew-council/"

[[params.social]]
name = "github"
url = "https://github.com/AndrewCouncil"

[security.exec]
allow = [
  '^(dart-)?sass(-embedded)?$',
  '^go$',
  '^git$',
  '^npx$',
  '^postcss$',
  '^tailwindcss$',
  '^zeditor$'
]

[taxonomies]
tag = "tags"
